package com.bala.adv_query;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class AppData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "APPDATA_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "APPDATA_ID_SEQ", name = "APPDATA_ID_GENERATOR")
    private java.lang.Long id;

    public AppData() {
    }
    
    public AppData(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}